Обновление кода
NeuroWorkers/UI_infra pull request #1
Opened 2024-11-15 17:33 UTC by Santas7

**Фамилия Имя:** Панюшкин Андрей

"стоит отметить что я не все там реализовал но свои 5,000 копеек вставлю аххаххаха"

Вот какие изменения я предлагаю:
- во-первых добавить requirements.txt
- во-вторых html должен быть более граммотно реализован и классы желательно именовать согласно методологии BEM CSS
- далее соответственно и файлик .css видоизмениться
- по js тоже внес правки дабы чтобы выглядело более нормально 

Касаемо части flask:
flask_ui.py необходимо переименовать в main.py
далее что не хватает как по мне
- осмысленных docstring, typehints
- обработки ошибок через тот же try-except, даже можно прямо с else и finally
- там где ты получаешь вопрос который якобы пришел - request.form['question'], у тебя нет никакой проверки что может привести к потенциальным проблемам в дальнейшем
- то есть как бы по предыдущему ну и в целом - не хватает валидации данных
- да и вообщем вместо request.form я бы рекомендовал юзать .json
- было бы здорово добавить логирование в код (через logging)
- ну и добавить обработчики ошибок например что-то типа @app.errorhandler, ..

В целом остальное гуд)

2024-11-15 18:04 UTC, the80hz commented on main.py
Верни оригинальное название файла

2024-11-15 18:15 UTC, the80hz requested changes
![image](https://github.com/user-attachments/assets/32c4bb39-568b-4774-b7d1-08377603567a)
Этот дизайн просто ~~говнище~~

2024-11-15 18:15 UTC, the80hz commented on main.py
Верни оригинальное название файла

2024-11-15 18:15 UTC, the80hz commented on requirements.txt
> +Flask=3.0.3
`Flask==3.0.3`

2024-11-15 18:26 UTC, the80hz approved these changes
lgtm

2024-11-16 12:02 UTC, Sv163Sam commented
@Santas7 1) Не вижу смысла добавлять req.txt из-за одного flask - это во-первых, во-вторых, код на flask на данной стадии - примитивно-базовые вещи, которые дозволительно писать и на более поздних версиях. 2) Не вижу в твоих изменениях координально-грамотных вещей. И, да, по поводу нэйминга, поверь мне, в реальном проде, никто по бумажкам с нотациями не работает. 3) Если ты считаешь, что вставить парочку лямбда-выражений и обернуть пару функций = выглядеть нормально - это бред. Это сильно ухудшает читаемость кода. 4) Нет смысла переименовывать в main, и как минимум, никто, никогда не называет "сервера" мэйнами. 5) По поводу обработки ошибок, можно, но обычно задача кодеров состоит в избавлении от них путем написания грамотного кода. 6) В чем, по-твоему, преимущества json?

2024-11-16 12:07 UTC, Sv163Sam commented
@the80hz Сама структура, стандартная; цвет букв, фона и т.д., хочешь инновационнее, напили, чекнем. А так просто времени особо нет, делать топовый дизайн, так сказать задача минимум выполнена)

2024-11-20 06:25 UTC, Santas7 commented
- в начальном коде ты не используешь форму в таком случае используй .json (ну или переделай html)
- как уже ранее говорил для более корректного именования лучше всего использовать BEM, но в целом для статических страниц думаю, что это не критично. 
- requirements.txt все равно должен быть (неизвестно на какой версии ты все там делал), ну и + думай о будущем.. вероятно по мимо flask будет что-то еще.
- function это уже древний синтаксис (так что стрелочные функции используем)
- стоит отметить что после всех проделанных изменений код стал выглядить более структурировано. (+ сократилось кол-во строк кода с 88 до 54)
- "в main, и как минимум, никто, никогда не называет "сервера" мэйнами" насчет именования ты не прав, main это просто стандартное именование. Ну в целом что main, что flask_ui все будет верно.

**Вроде как за все пояснил.**

![Снимок экрана 2024-11-19 в 9 21 32 PM](https://github.com/user-attachments/assets/078d7149-2347-44d6-9f4f-258374591944)

2024-11-25 12:41 UTC, closed without merging